# Generated by Django 4.0.1 on 2022-02-21 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='people_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
