# Generated by Django 4.0.3 on 2023-07-18 20:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatar.svg', max_length=255, verbose_name='image'),
        ),
    ]
